### ISSUE TITLE
Image gets oversaturated and baked in after turning off node

### ISSUE THREAD

**Issue by Lazthearist2** [Extraltodeus/ComfyUI-AutomaticCFG#11]
The node works fine until i turn it off to check the generation without the AutomaticCFG node (i use the base one)
I'll include three picture 
**The First Image is without the node ( generating before turning it on)**
![image](https://github.com/Extraltodeus/ComfyUI-AutomaticCFG/assets/80925144/8c133fc4-d89f-4790-9d81-671cafb2e00d)
**The Second Image is AutomaticCFG turned on**
![image](https://github.com/Extraltodeus/ComfyUI-AutomaticCFG/assets/80925144/a45b0270-9c71-4951-bf07-7d447872fcd0)
**The Third image is the generation after i turn off the AutomaticCFG node**
![image](https://github.com/Extraltodeus/ComfyUI-AutomaticCFG/assets/80925144/1e007e30-a812-4a17-9fbf-385d3f3a8e30)
I'll also provide the workflow if it's needed
[workflow (2).json](https://github.com/Extraltodeus/ComfyUI-AutomaticCFG/files/15099376/workflow.2.json)

**Comment by Extraltodeus** [comment]
Hello! You have to start a batch with the "sigma boost" toggle turned off in order to unpatch the function.

**Comment by Lazthearist2** [comment]
ohhh, it seems like i totally skipped that text! sry my bad, thanks for the help!
