### ISSUE TITLE
'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by aa2246740** [Extraltodeus/ComfyUI-AutomaticCFG#19]
when I m using the example , it shows:Error occurred when executing CLIPTextEncode:  'NoneType' object has no attribute 'shape'

**Comment by Extraltodeus** [comment]
Not sure which example you're talking about. While for sure I might miss updating example workflows, I can not guess which error you are encountering.

Kindly open a ticket with helpful informations so I may guess what the actual issue is.
