### ISSUE TITLE
Extreme Slowdown

### ISSUE THREAD

**Issue by PrometheusDante** [Extraltodeus/ComfyUI-AutomaticCFG#21]
Since the most recent update only the first pass of my workflow runs sped up, the second pass already comes to a screeching halt at step one of the second pass due to capping my vram. No matter which auto-cfg node I tried the result was the exact same. Even with the new node and preset setting to "old auto-cfg" it did not change anything. 
No error messages, nothing in the console, no difficulties installing/updating the nodes. 
All I could observe was the vram getting overloaded by seemingly not being released as usual after the first pass. Deleting the node and starting the queue again does not solve the issue, as the vram retention seems to stay until restart. Even when manually using the "Cleanup Of GPU Usage" in the right-click context menu from the easyuse node to release the vram and starting a new queue without any auto-cfg node it still runs into the same issue at the second pass.

**Comment by Extraltodeus** [comment]
That is strange! I have no such issue so I need more elements in order to help you. Do you have the same problem if you do not use the node at all for example? Which UI do you use? Forge or Comfy? Are you all up to date?

**Comment by PrometheusDante** [comment]
I'm using comfyui and I'm all updated. When not using the node at all everything is fine. But as soon as I run it even once it will require a restart to get the vram overload issue handled. And no errors whatsoever, it just slows down as you'd expect from running out of vram and proceeds with absurd slowness where even canceling takes about a minute to actually happen. When you keep an eye on your vram during a multi-pass workflow, even in a setting without overloading the vram it does still go up higher with the node than without. I might be able to build a workflow that just about runs, but runs slower with the node than without to illustrate that, if it's helpful. Got 16gb vram with a 4080, everything up to date btw. if that's relevant.

**Comment by djbielejeski** [comment]
I am also getting my VRAM maxed out when this is enabled. Just using this node
![image](https://github.com/Extraltodeus/ComfyUI-AutomaticCFG/assets/2463282/c3fa2522-e27e-44a2-906f-c42681c8f0ba)

**Comment by djbielejeski** [comment]
Enabled followed by disabled

![image](https://github.com/Extraltodeus/ComfyUI-AutomaticCFG/assets/2463282/bc7fc321-686c-4ce4-9fed-bdf8ba1ee50e)

**Comment by ManOrMonster** [comment]
Yep, same here. Narrowed it down to this node. Use my workflow here: https://civitai.com/models/423960
Disable the AutomaticCFG node before running, and use InstantID. Works fine. Enable AutomaticCFG, get OOM, or extreme slowdown. Something got borked from today's updates somehow, and it only seems to be affecting InstantID from my tests.

**Comment by ManOrMonster** [comment]
I tried it again after replacing the "Automatic CFG" node with "Automatic CFG - Preset Loader" and had the same issue.

**Comment by Extraltodeus** [comment]
Should be fixed now, can you try?
@pamparamm Thank you :D

**Comment by ManOrMonster** [comment]
It's working for me now!

**Comment by Extraltodeus** [comment]
Awesome! I close the ticket! 😁
