### ISSUE TITLE
UPDATING: Git Pull not working today

### ISSUE THREAD

**Issue by Piscabo** [Extraltodeus/ComfyUI-AutomaticCFG#22]
H:\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG>git pull
remote: Enumerating objects: 265, done.
remote: Counting objects: 100% (265/265), done.
remote: Compressing objects: 100% (184/184), done.
error: 481 bytes of body are still expectedB | 67.00 KiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by Extraltodeus** [comment]
uuuuh tbh like that I have no idea. Feels like it's more a problem on your side? Try deleting the folder and redownloading maybe?

**Comment by Extraltodeus** [comment]
Any news?
