### ISSUE TITLE
Grey images

### ISSUE THREAD

**Issue by tombearx** [Extraltodeus/ComfyUI-AutomaticCFG#29]
The extension returns a grey (getting greyer after each step) like image on my setup in the last 3 days after I updated MacOS and ComfyUI at the same time (M1 Pro, MacOS 14.5, python 3.12). Tried to reinstall ComfyUI, packages, change settings. Nothing helped. Any ideas?

I love the extension, hope someone could help.
![ComfyUI_00027_](https://github.com/Extraltodeus/ComfyUI-AutomaticCFG/assets/162094659/dbfd764b-80a0-4ff1-b8bc-fe29b3ef33b6)

**Comment by Extraltodeus** [comment]
Hello!

I see that you're using some post-cfg nodes like SAG and PAG. Self-Attention guidance uses the negative and therefore you should disable the "boost" toggle since it disables the negative for 60% of the generation. This should solve your issue.

**Comment by tombearx** [comment]
> Hello!
> 
> I see that you're using some post-cfg nodes like SAG and PAG. Self-Attention guidance uses the negative and therefore you should disable the "boost" toggle since it disables the negative for 60% of the generation. This should solve your issue.

Thanks, it worked! 
For some reason, that was not a case before an update.
