### ISSUE TITLE
Any special consideration to use it with LCMs?

### ISSUE THREAD

**Issue by vicentecarro** [Extraltodeus/ComfyUI-AutomaticCFG#3]
It's mentioned that for regular models it should be set to 8, but no idea about LCMs.

**Comment by Extraltodeus** [comment]
I've slipped a turbo examplée but haven't tried with lcm. Try to use it like you would normally at first and then adjust. It should work as well since in toes in between steps. Now of course if you do only 3-4 steps it might have a low influence. Quite frankly I don't know.
