### ISSUE TITLE
 (IMPORT FAILED)   after comfy update

### ISSUE THREAD

**Issue by AlexD81** [Extraltodeus/ComfyUI-AutomaticCFG#31]
hi, I've updated comfy today, and AutomaticCFG stopped working.   Tried to uninstall and install it,  it doesn't helps.....  

Cannot import C:\Users\***\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG module for custom nodes: name 'CLIPTemperaturePatch' is not defined

"C:\Users\***\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG\__init__.py", line 19, in <module>
    "Temperature settings CLIP": CLIPTemperaturePatch,
NameError: name 'CLIPTemperaturePatch' is not defined

**Comment by AlexD81** [comment]
I've deleted  line 19,      and it starts to work.  Im not a dev, dont know what's problem,  Could you pls fix it?

**Comment by GalaxyTimeMachine** [comment]
Came here with the same problem.

**Comment by tuangd** [comment]
I imported the CLIPTemperaturePatch in __init__.py and it works.

in line 2 of __init__.py I added CLIPTemperaturePatch at the end.

`from .experimental_temperature import ExperimentalTemperaturePatchSDXL,ExperimentalTemperaturePatchSD15,CLIPTemperaturePatch`

I am guessing the dev forgot to import that class.

**Comment by Piscabo** [comment]
Also same problem. Will do the mod for myself in the meantime.
Traceback (most recent call last):
  File "C:\AI_Files\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI_Files\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG\__init__.py", line 19, in <module>
    "Temperature settings CLIP": CLIPTemperaturePatch,
                                 ^^^^^^^^^^^^^^^^^^^^
NameError: name 'CLIPTemperaturePatch' is not defined

Cannot import C:\AI_Files\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG module for custom nodes: name 'CLIPTemperaturePatch' is not defined

**Comment by whmc76** [comment]
i encounter the same issue

**Comment by Extraltodeus** [comment]
My bad! forgot to import it in the ini file! It's fixed :D
