### ISSUE TITLE
Explain "hard_mode"

### ISSUE THREAD

**Issue by ghostsquad** [Extraltodeus/ComfyUI-AutomaticCFG#34]
Can you explain the "hard_mode" toggle please?

**Comment by Extraltodeus** [comment]
Hello! It's just a slight difference in the way it measures the values. It generaly gives more predictable results.

**Comment by DarkAlchy** [comment]
Also hasn't worked for anyone I have asked as we all get black boxes.  Even get that, sometimes, from boost.

**Comment by Extraltodeus** [comment]
Hello! 

The hard mode is simply a way of evaluating the correction which is a bit more precise. This is what I use by default too.

The boost stops the uncond from being generated at around 40% off the steps. If you use any post-cfg node making use of it, it will generate a black image. SAG may do that, as for PAG you can set it to stop  when the sigmas reaches 1 (which is ~7% of the total sigmas for SDXL/1.5)
