### ISSUE TITLE
Sorry, new here and don't understand all the lingo.. how do I install this?

### ISSUE THREAD

**Issue by abclution** [Extraltodeus/ComfyUI-AutomaticCFG#35]
Sorry to be an idiot.

I cannot understand if this is a custom node, a config? 

I know its not a lora but I'm confused if this is a workflow? Little install hint plx. :)

**Comment by brodieferguson** [comment]
It's custom nodes for ComfyUI. You can get [https://github.com/ltdrdata/ComfyUI-Manager](ComfyUI Manager) and use that to install projects like this if doing it manually is confusing right now.
