### ISSUE TITLE
Could this be used outside ComfyUI?

### ISSUE THREAD

**Issue by andupotorac** [Extraltodeus/ComfyUI-AutomaticCFG#39]
We love what you built and would like to explore using it outside of ComfyUI. Would this be an issue and require a lot of changes to the code?

**Comment by Extraltodeus** [comment]
Hello!

Well it REALLY depends on which feature. For the auto-cfg itself it should not be over-complicated. As the core logic is to use the cond/uncond to generate the denoised result as if using a CFG scale of 8. Then, take for each channel the mean of 25% of the highest values, the mean of 25% of the lowest values (as positive values) so you get two positive numbers. Average them and you get one which is what is used for the measure. After experimenting while developping this tool I settled on 0.8. Which is conveniently the default CFG divided by 10. So you then use this result to make a new denoised result using a CFG scale which will be basically doing 8 * (CFG scale / 10) / the result. So if the result happens to be 1.6 the new scale will become 4 so to correct the aim.

The used values are all arbitary decision based on experimentation.
