### ISSUE TITLE
Encoded Patreon Advertisement

### ISSUE THREAD

**Issue by BaconIsSuperTasty** [Extraltodeus/ComfyUI-AutomaticCFG#42]
The default behavior of using the AutomaticCFG node is that it prints an advertisement for the repo owner's patreon.  I am not against the idea of advertising one's patreon, but the ad takes up 16 lines in the console with 5 lines being text-every time the node is run, This is very inconvenient- I look at the console regularly for relevant information for current and past gens, and that information is getting flooded out every time the node triggers. 
![Screenshot 2024-06-16 173842](https://github.com/Extraltodeus/ComfyUI-AutomaticCFG/assets/162859140/92682486-c3a9-47d6-9088-ba7e9ff14650)

A second issue is that this ad is encoded within nodes_.py as "check_string" and "support_string" which is then subsequently called to be decoded at line #578 with the support_function() function, which was defined at line 26.  I consider this a major issue, as it is a layer of obfuscation who's only intent can be to hide where the ad is stored, and thus make it more difficult for someone to remove.  This is an issue because it is a violation of trust with the end user, and I believe that it violates the spirit of open source.  Users should be able to view the code without any unnecessary obfuscation so that when we do run into obfuscation, we can be more certain that it is due to a bad actor trying to hide something, and not something more innocent.  [Bad actors have already used the idea of comfyui custom nodes as a way to compromise people's computers](https://www.reddit.com/r/comfyui/comments/1dbls5n/psa_if_youve_used_the_comfyui_llmvision_node_from/)- and the level of due-diligence that the average user can put in is limited due, in part, to their lack of knowledge of programming.  We need to be able to trust you.

I suggest that the advertisement is changed to 1-2 lines, not be obfuscated, and show up only once per start up.

**Comment by Extraltodeus** [comment]
Let's be honest, the essence of your message is really there:
> I suggest that the advertisement is changed to 1-2 lines, not be obfuscated, and show up only once per start up.

So I read that message as I eat sunflower oil covered cheap pastas, then I check my subscriber count and it remained the same. I check the nicknames and pretty sure you're not included.

If it forces you to understand what toddler-level of obfuscation can be with python then good! I enhanced your knowledge about safety!

It only violates the space of your terminal.

Your whole message is only about your low tolerance to discomfort.

And you should there either subscribe to my Patreon, where it tells you how to remove  the message, or go tell your mom that the developper working for free refused to submit to your tantrum.

**Comment by BaconIsSuperTasty** [comment]
As I said in my initial response, I don't hold it against you that you want people to be aware of your patreon.  However, I am saddened that you have chosen to respond to my post with insults and vitriol.  I would rather not engage in such hostile behaviour, so I want to try to work with you to break down this issue.  

The main advantage(or perhaps purpose) the advertisement has is that it ensures that the user will see it, which then ensures that they are aware you have a patreon, which will then hypothetically lead to more patreon subscribers.  It makes sense that you would want to extract value from your work- the saying goes that if you are good at something to never do it for free. 
However, the advertisement comes at a cost to the user- 16 lines of the console are consumed after every generation.  This is highly inconvenient since it floods out information from the prior generation.  Any other information the user may need to see takes more time to find, and this time only goes up the further back the information needed is.  You have decided that you are ok with this cost to the user- **_what is your rationalization for why the size and frequency of your advertisement is a reasonable trade-off for the user?_**  

Since I am interested in reaching a mutual understanding, I will give some counterpoints that I have thought of.  
1. Because the node is open source, the user can find and disable the advertisement
2. Because the node is free, the user can choose to just not use the node 

Response to counter-points:
1. The advertisement has been obfuscated in the source code, which raises the difficulty of the average user to be able to remove the ad.  The only possible reason for you to go out of your way to obfuscate the code for the advertisement is to prevent (some) people from being able to remove the ad.  If putting in the advertisement is ok, in part,  because the user can just remove it,  That by extension that means any attempt to increase the advertisements resistance to removal violates the integrity of that reasoning.  Since you have done just that, by obfuscating the advertisement in the code, you cannot take the position that the advertisement is ok, in part, due to the ability of the user to remove it, since some users will not be able to remove it.
2.  I have no counter to this counter-point.

Before I end this post, I want you to consider one thing- what do **_you_** do when you encounter a repeatedly unavoidable advertisement?  My experience is that once a person gets annoyed enough they will go out of their way to not buy the thing that is being repeatedly advertised to them.  If your goal is to maximize the amount of patreon subscribers your hard work has earned, then you would have to acknowledge that not only is there a rate of diminishing returns based on how aggressively you advertise your patreon, but also a point where the gain turns into a loss.

**Comment by Extraltodeus** [comment]
Your arguments weight as much as your contribution. Which amounts to nothing.
