### ISSUE TITLE
 Cannot import E:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-AutomaticCFG module for custom nodes: 

### ISSUE THREAD

**Issue by Charlo-O** [Extraltodeus/ComfyUI-AutomaticCFG#49]
cannot import name 'set_model_options_patch_replace' from 'comfy.model_patcher' (E:\ComfyUI-aki-v1.1\comfy\model_patcher.py)
![fe0914fc3346bae9cabe09b094ad6b0](https://github.com/Extraltodeus/ComfyUI-AutomaticCFG/assets/49369951/75940e1d-7527-4dba-a1ed-341a578e5ed7)

**Comment by Extraltodeus** [comment]
Hello! Are you using some fork of ComfyUI (I see "aki" in the path)?

![image](https://github.com/user-attachments/assets/3a0d9a11-e1d0-431a-bf0d-18af33770366)

It seems that there is an incompatibility

**Comment by Charlo-O** [comment]
yes,tks for your answer,i know
