### ISSUE TITLE
Don't work with cfgpp (except from distance samplers)

### ISSUE THREAD

**Issue by fgdfgfthgr-fox** [Extraltodeus/ComfyUI-AutomaticCFG#52]
I notice automatic cfg doesn't work with cfgpp samplers like euler_cfg_pp included in ComfyUI, the produced images are always fried. However, cfgpp samplers from distance samplers are fine, although they would produce the exact same result as their non-cfgpp version.

**Comment by Extraltodeus** [comment]
Hello, it is due to the "boost" feature which disables the negative prediction near the end. The CFGpp sampler expect a negative prediction.

You can use the node named [support empty uncond](https://github.com/Extraltodeus/pre_cfg_comfy_nodes_for_ComfyUI) which solves this issue.

**Comment by fgdfgfthgr-fox** [comment]
It still doesn't work... It output an error instead.
```
  File "/mnt/2878EBCCAED823C6/ComfyUI/custom_nodes/pre_cfg_comfy_nodes_for_ComfyUI/nodes.py", line 481, in patch
    m.set_model_sampler_pre_cfg_function(support_empty_uncond)
  File "/mnt/2878EBCCAED823C6/ComfyUI/comfy/model_patcher.py", line 181, in set_model_sampler_pre_cfg_function
    self.model_options = set_model_options_pre_cfg_function(self.model_options, pre_cfg_function, disable_cfg1_optimization)
  File "/mnt/2878EBCCAED823C6/ComfyUI/comfy/model_patcher.py", line 74, in set_model_options_pre_cfg_function
    model_options["sampler_pre_cfg_function"] = model_options.get("sampler_pre_cfg_function", []) + [pre_cfg_function]
TypeError: unsupported operand type(s) for +: 'function' and 'list'
```
![2024-09-06 22-22-21屏幕截图](https://github.com/user-attachments/assets/bda949b4-c3e6-4285-839a-2b033bf5f3c6)

**Comment by Extraltodeus** [comment]
Update automatic CFG

**Comment by fgdfgfthgr-fox** [comment]
> Update automatic CFG

It's working now, thanks!

**Comment by fgdfgfthgr-fox** [comment]
Wait... It will still fry the image if the cfg is set exactly to 1 (0.9 or 1.1 won't trigger it).

**Comment by Extraltodeus** [comment]
Well CFGpp is a different sampler with a different way to work. The Distance version that I made includes a detection of an empty negative (its a latent full of 0). I can't adapt it to every use case :)

**Comment by fgdfgfthgr-fox** [comment]
Okay... I guess that means we have to live with it then.
